### ISSUE TITLE
ゲーム情報処理部にリクエスト

### ISSUE THREAD

**Issue by RyoMazaki** [omuraisupan/advance1B#1]
ボタンの表示、非表示（もしくは活性、非活性）の切り替えにboolean型でtrueかfalseを返す関数が欲しいです。
ターンの種類が複数あるのでその分欲しいです。

**Comment by omuraisupan** [comment]
プレイヤーが自分のターンかどうかを判定するための関数ですか？

**Comment by RyoMazaki** [comment]
ごめんめちゃくちゃ言葉足らずだった
その通りです。
